### ISSUE TITLE
user's id in JWT token should be stored as `sub`

### ISSUE THREAD

**Issue by spawn-guy** [nikitamarcius/graphql-authentication-register-profile#1]
> Subject (sub) - identifies the subject of the JWT;
From https://en.m.wikipedia.org/wiki/JSON_Web_Token

In this repo you store it as `id` field. Which should be `sub` according to Standard

**Comment by nikitamarcius** [comment]
updated 18e32f4644d8315b96d366b6dfa25fd15dc3058f
